
if GetGlobalInt( "CurrentGamemode" ) != 1 then return end

TEAM_VISITOR = 1
TEAM_ADMIN = 2
TEAM_SURVEYBOSS = 3
TEAM_SURVEY = 4
TEAM_DEV = 5
TEAM_TECH = 6
TEAM_BIO = 7
TEAM_MEDIC = 8
TEAM_SERVICE = 9
TEAM_GMAN = 10
TEAM_MARINE = 11
TEAM_MARINEBOSS = 12
TEAM_WEPBOSS = 13
TEAM_WEPMAKER = 14
TEAM_SECURITYBOSS = 15
TEAM_SECURITY = 16
