
if GetGlobalInt( "CurrentGamemode" ) != 3 then return end

TEAM_REFUGEE = 1
TEAM_RESISTANCELEADER = 2
TEAM_REBEL = 3
TEAM_REBELMEDIC = 4
TEAM_COMBINEELITE = 5
TEAM_COMBINEGUARD = 6
TEAM_COMBINESOLDIER = 7
TEAM_COMBINEGUARDSHOTGUN = 8
